---
title: "Aspectos demográficos"
format: html
---

```{r pacotes e input de dados}
#| include: false
library(srvyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(tinytable)

funcoes <- list.files("R", pattern = "\\.R$", full.names = TRUE)
sapply(funcoes, source, .GlobalEnv)

# baixa_dados(year = 2023)
# baixa_dados(year = 2024)

design <- le_dados()
#design2023 <- le_dados(year = 2023)
```


```{r}
#| label: tbl-domicilios
#| tbl-cap: "População residente - Ceará, Nordeste e Brasil - 2023 - 2024"

populacao <- bind_rows(
  design |> 
    filter(UF=="Ceará") |> 
    mutate(grupo = "Ceará", ano = 2024) |> 
    group_by(ano, grupo) |> 
    survey_count(name = "total_pop"),
  design2023 |> 
    filter(UF=="Ceará") |> 
    mutate(grupo = "Ceará", ano = 2023) |> 
    group_by(ano, grupo) |> 
    survey_count(name = "total_pop"),
  design |> 
    filter(UF%in%c("Maranhão", "Piauí", "Ceará", "Rio Grande do Norte",
                  "Paraíba", "Pernambuco", "Alagoas", "Sergipe", "Bahia")) |> 
    mutate(grupo = "Nordeste", ano = 2024) |> 
    group_by(ano, grupo) |> 
    survey_count(name = "total_pop"),
  design2023 |> 
    filter(UF%in%c("Maranhão", "Piauí", "Ceará", "Rio Grande do Norte",
                  "Paraíba", "Pernambuco", "Alagoas", "Sergipe", "Bahia")) |> 
    mutate(grupo = "Nordeste", ano = 2023) |> 
    group_by(ano, grupo) |> 
    survey_count(name = "total_pop"),
  design |> 
    mutate(grupo = "Brasil", ano=2024) |> 
    group_by(ano, grupo) |> 
    survey_count(name = "total_pop"),
  design2023 |> 
    mutate(grupo = "Brasil", ano=2023) |> 
    group_by(ano, grupo) |> 
    survey_count(name = "total_pop")
)

```
::: {custom-style="Anotação"}
*Fonte: IBGE. PNAD Contínua Anual 1ª Entrevista*
:::

```{r}
#| label: fig-situacao
#| fig-cap: "População segundo Unidade Federativa (milhões de pessoas) - 2024"

pop_estados <- design |> 
  group_by(UF) |> 
  survey_count(name = "total_pop")

pop_estados |> 
  arrange(desc(total_pop)) |> 
  mutate(destaque = ifelse(UF == "Ceará", "Ceará", "Outros estados")) |> 
  ggplot(aes(x = fct_rev(fct_reorder(UF, total_pop)), y = total_pop, fill = destaque)) +
  geom_col() +
  geom_text(
    aes(label = scales::number(total_pop / 1e6, accuracy = 0.1)),
    hjust = -0.1, 
    size = 3,
    angle = 90
  ) +
  scale_fill_manual(values = c("Ceará" = "#F59C00", "Outros estados" = "#26A737")) +
  scale_y_continuous(
    labels = scales::label_number(scale = 1e-6, suffix = "M"),
    expand = expansion(mult = c(0, 0.2))  # Adiciona espaço no topo para os rótulos
  ) +
  labs(
    #title = "População por Estado Brasileiro - 2024",
    x = "Estado",
    y = "População (milhões)",
    fill = NULL
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    legend.position = "bottom",
    panel.grid.major.x = element_blank()
  )

ggsave("output/pop_estados.png", width = 20, height = 15, units = "cm")
```
::: {custom-style="Anotação"}
*Fonte: IBGE. PNAD Contínua Anual 1ª Entrevista*
:::

```{r}
#| fig-cap: "População residente, segundo sexo e grupo etário - Ceará - 2024"

piramide_etaria <- design |> 
  filter(UF == "Ceará") |> 
  group_by(V2007, VD2006) |> 
  survey_count(name = "total_pop") 

piramide_etaria |> 
  mutate(total_pop = if_else(V2007 == "Homem", -total_pop, total_pop)) |> 
  ggplot(aes(VD2006, total_pop, fill = V2007))+
  geom_col() +
  coord_flip() +
  scale_y_continuous(
    labels = function(x) scales::number(abs(x) / 1000, suffix = "k"),
    breaks = seq(-400000, 400000, 100000)
  ) +
  scale_fill_manual(
    values = c("Homem" = "#26A737", "Mulher" = "#F59C00"),
    labels = c("Homem" = "Homens", "Mulher" = "Mulheres")
  ) +
  labs(
    #title = "Pirâmide Etária - Ceará - 2024",
    x = "Faixa Etária",
    y = "População (milhares)",
    fill = NULL
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    legend.position = "bottom",
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text = element_text(size = 10)
  ) +
  geom_vline(xintercept = 0, color = "gray50", linetype = "dashed", linewidth = 0.3)

ggsave("output/piramide_etaria.png", width = 20, height = 15, units = "cm")
```
::: {custom-style="Anotação"}
*Fonte: IBGE. PNAD Contínua Anual 1ª Entrevista*
:::

```{r}
#| tbl-cap: "População residente segundo cor ou raça declarada - Ceará - 2023-2024"

raca <- design |> 
  filter(UF == "Ceará") |> 
  mutate(V2010 =  fct_other(V2010, keep = c("Branca", "Preta", "Parda"))) |> 
  group_by(V2010) |> 
  summarise(populacao = survey_total(),
            proporcao = survey_prop())
raca
```
::: {custom-style="Anotação"}
*Fonte: IBGE. PNAD Contínua Anual 1ª Entrevista*
:::

```{r}
#| fig-cap: "Proporção de pessoas responsáveis por domicílio segundo sexo - Ceará - 2024"

sexo_responsavel <- design |> 
  filter(UF=="Ceará"&V2005=="Pessoa responsável pelo domicílio"&!is.na(V2007)) |> 
  group_by(V2007) |> 
  summarise(proporcao = survey_prop())

sexo_responsavel |> 
  mutate(
    ymax = cumsum(proporcao),
    ymin = c(0, head(ymax, n = -1)),
    labelPosition = (ymax + ymin) / 2,
    label = paste0(V2007, "\n", scales::percent(proporcao, accuracy = 0.1))
  )  |> 
  ggplot(aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = V2007)) +
  geom_rect() +
  geom_text(
    aes(x = 3.5, y = labelPosition, label = label),
    size = 5,
    fontface = "bold",
    color = "white"
  ) +
  scale_fill_manual(values = c("Homem" = "#26A737", "Mulher" = "#F59C00")) +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  labs(
    #title = "Pessoa responsável pelo domicílio por sexo - Ceará - 2024"
  ) +
  theme_void() +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    legend.position = "none"
  )

ggsave("output/sexo_responsavel.png", width = 20, height = 15, units = "cm")
```
::: {custom-style="Anotação"}
*Fonte: IBGE. PNAD Contínua Anual 1ª Entrevista*
:::
